[global]

[theme]
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#009900"

# Background color for the main content area.
backgroundColor = "#009900"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#333333"

# Color used for almost all text.
#textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =
